### ISSUE TITLE
Change to use Helpers in v1.4.4

### ISSUE THREAD

**Issue by TonyM1958** [TonyM1958/HA-FoxESS-Modbus#19]
Previous configurations required you to edit 'template.yaml' after installation to set values for 'Install Date', 'Battery Size' and optionally 'CT2 Handling' and 'Load Correction'.

This caused problems when the integration was updated through HACS as the values were over-written and set back to the default values.

From v1.4.4, these input values have been moved to Helpers. This requires the following lines to added to 'configuration.yaml':

```
# input values for configuring integration:
input_datetime:
  install_date:
    # install date for battery life calculation.
    name: Install Date
    has_date: true
    has_time: false
input_number:
  battery_size:
    # rated size of 1 battery for SoH calcuation.
    name: Battery Size
    mode: box
    max: 10
    min: 2
    step: 0.01
  ct2_handling:
    # how to use CT2
    name: CT2 Handling
    mode: box
    max: 3
    min: 0
  load_correction:
    # fix out of bounds load energy values
    name: Load Correction
    mode: box
    max: 429_496_729.5
    min: 0
    step: 0.1
```

After this change has been made and HA has restarted, the values can be configured through Helpers as described [here](https://github.com/TonyM1958/HA-FoxESS-Modbus/wiki/Installing-and-Configuring-HA-FoxESS-Modbus#configure-helpers)
